"use client";
import { motion } from "framer-motion";

const moments=[
  {year:"01",title:"A familiar face",text:"Somewhere between ordinary days and passing glances, we became two people who kept finding reasons to talk."},
  {year:"02",title:"A little more often",text:"A follow, a few messages, long conversations — and slowly, the familiar became someone we looked forward to."},
  {year:"03",title:"Our kind of forever",text:"What began quietly grew into a life we wanted to build together. Now we get to celebrate the next chapter with you."},
];
export default function OurStory(){return <section id="story" className="relative overflow-hidden bg-[#f2ede2] px-5 py-24 sm:px-8 sm:py-32"><div className="absolute left-0 top-0 h-80 w-80 -translate-x-1/3 -translate-y-1/3 rounded-full bg-[#a8b09a]/25 blur-3xl"/><div className="relative z-10 mx-auto max-w-6xl"><div className="grid gap-14 lg:grid-cols-[.75fr_1.25fr] lg:gap-24"><div className="lg:sticky lg:top-32 lg:h-fit"><p className="text-[9px] uppercase tracking-[.36em] text-[#747a5a]">A little history</p><h2 className="font-display mt-4 text-6xl leading-[.86] text-[#4e4035] sm:text-8xl">Our<br/><span className="font-script text-[#747a5a]">story</span></h2><div className="section-rule mt-8"/><p className="mt-6 max-w-sm font-display text-xl leading-7 text-[#4e4035]/70">Not every love story needs a grand beginning. Ours just needed a little time.</p></div><div className="relative">{moments.map((m,i)=><motion.article key={m.year} initial={{opacity:0,y:35}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-70px'}} transition={{delay:i*.08}} className="relative border-t border-[#4e4035]/15 py-9 sm:py-12"><div className="grid gap-5 sm:grid-cols-[90px_1fr]"><span className="font-display text-xl text-[#747a5a]">{m.year}</span><div><h3 className="font-display text-4xl text-[#4e4035] sm:text-5xl">{m.title}</h3><p className="mt-4 max-w-xl text-sm leading-7 text-[#4e4035]/68">{m.text}</p></div></div></motion.article>)}</div></div></div></section>}
